version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    # No expongas puertos porque es un bot que corre en background
